/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VouchMe } from "./VouchMe";
export * as factories from "./factories";
export { VouchMe__factory } from "./factories/VouchMe__factory";
